# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20160624_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='parent',
        ),
    ]
