# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_auto_20160624_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifieds.Region'),
        ),
    ]
