# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0006_auto_20160625_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos'),
        ),
    ]
